#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.editor_sources, "*.cpp")

# Only include our Gameable plugin subtree explicitly; upstream gizmos/tiles are elsewhere in 4.5.
SConscript("gameable/SCsub")
