#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.editor_sources, "*.cpp")
# register_types.cpp is already matched by the glob above; avoid duplicate object warnings


